Added in cluster-config configure etcd.

diff --git a/cluster-config b/cluster-config
--- a/cluster-config
+++ b/cluster-config
@@ -1,5 +1,6 @@
 #!/bin/bash
-PATH_CLUSTER_INSTALLED="/etc/smilart/cluster_installed";
+PATH_CONFIGURE_DIR="/etc/smilart";
+PATH_CLUSTER_INSTALLED="$PATH_CONFIGURE_DIR/cluster_installed";
 ETCD_PORT=2379;
 
 #exist dialog?
@@ -46,7 +47,7 @@ error_func() {
 }
 
 # valid_ip_func <ip>
-# valid_ip_func 192.168.1.1 
+# valid_ip_func 192.168.1.1
 function valid_ip_func() {
   if ! [[ $1 =~ ^(25[0-5]|2[0-4][i0-9]|[0-1][0-9]{2}|[0-9]{2}|[0-9])(\.(25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[0-9]{2}|[0-9])){3}$ ]]; then
     error_func "${LOG_ERROR[3]}";
@@ -70,17 +71,17 @@ while [[ $EXIT_FORM == "0" ]];do
       2>&1 1>&3)
   DIALOG_RETURN_VALUE=$?
   exec 3>&-
-  
+
   if [[ $DIALOG_RETURN_VALUE == 1 || $DIALOG_RETURN_VALUE == 255 ]]; then
     exit 1;
   fi;
-  
+
   #Empty ?
   if [[ -z "$FORM_CLUSTER" ]]; then
      error_func "${LOG_ERROR[1]}";
      continue
   fi
-   
+
   if [[ "$FORM_CLUSTER" == "2" ]];then
       # display values just entered
       # open fd
@@ -96,7 +97,7 @@ while [[ $EXIT_FORM == "0" ]];do
        2>&1 1>&3)
        DIALOG_RETURN_VALUE=$?
        exec 3>&-
-      
+
       #ESC in dialog?
       if [[ $DIALOG_RETURN_VALUE == 1 || $DIALOG_RETURN_VALUE == 255 ]]; then
         continue
@@ -107,7 +108,7 @@ while [[ $EXIT_FORM == "0" ]];do
         error_func "${LOG_ERROR[2]}";
         continue
       fi;
-      
+
       #Valid ip?
       valid_ip_func $FORM_IP;
 
@@ -125,9 +126,79 @@ while [[ $EXIT_FORM == "0" ]];do
   EXIT_FORM="1";
 done;
 
+
+
+#*******************Configuring etcd************#
 #*******************Save to file****************#
 echo "$CLUSTER_INSTALLED" > $PATH_CLUSTER_INSTALLED;
 if [[ $? != 0 ]];then
   echo -e "\E[31mERROR: Cannot create '$PATH_CLUSTER_INSTALLED'.">&2;tput sgr0;
   exit 1;
+fi;
+
+#Configuring master etcd if CLUSTER_INSTALLED is not "single"
+if [[ $CLUSTER_INSTALLED != "single" ]]; then
+    etcdctl --peers=$FORM_IP:$ETCD_PORT member add `hostname` $HOST_IP;
+    if [ $? -ne 0 ]; then
+        echo -e "\E[31m Error configuring master etcd!" >&2;tput sgr0;
+        exit 1;
+    fi;
+fi;
+
+#Stopping daemon etcd
+sudo systemctl daemon-reload;
+sudo systemctl stop etcd2.service;
+sudo systemctl stop etcd2-cluster.service;
+#Enable service etcd
+sudo systemctl enable etcd2.service > /dev/null;
+#Clearing cache etcd
+sudo rm -f -R /var/lib/etcd2/* > /dev/null 2>&1;
+
+function create_etcd2_service_func(){
+    local line PEER_URL INITIAL_CLUSTER NAME;
+    HOST_IP=`cat /etc/systemd/network/static.network | grep 'Address' | sed s#"Address="##g | awk -F '/' ' {print $1} '`;
+
+    # Configure etcd2.service
+    echo "ETCD_DATA_DIR=\"/var/lib/etcd2\""                                        > $PATH_CONFIGURE_DIR/etcd2.service.env;
+    echo "ETCD_NAME=\"`hostname`\""                                               >> $PATH_CONFIGURE_DIR/etcd2.service.env;
+    echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380\""                         >> $PATH_CONFIGURE_DIR/etcd2.service.env;
+    echo "ETCD_LISTEN_CLIENT_URLS=\"http://$HOST_IP:2379,http://127.0.0.1:2379\"" >> $PATH_CONFIGURE_DIR/etcd2.service.env;
+    echo "ETCD_ADVERTISE_CLIENT_URLS=\"http://$HOST_IP:2379\""                    >> $PATH_CONFIGURE_DIR/etcd2.service.env;
+
+    # etcd2 prestart configure
+
+    echo "ETCD_DATA_DIR=\"/var/lib/etcd2\""                                          > $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_NAME=\"`hostname`\""                                                 >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_LISTEN_CLIENT_URLS=\"http://$HOST_IP:2379,http://127.0.0.1:2379\""   >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_ADVERTISE_CLIENT_URLS=\"http://$HOST_IP:2379\""                      >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_INITIAL_CLUSTER_TOKEN=\"smilart-cluster\""                           >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    if [[ "$CLUSTER_INSTALLED" == 'single' ]];then
+
+      echo "ETCD_INITIAL_ADVERTISE_PEER_URLS=\"http://$HOST_IP:2380\""              >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+      echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380,http://127.0.0.1:2380\""   >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+      echo "ETCD_INITIAL_CLUSTER_STATE=\"new\""                                     >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+      echo "ETCD_INITIAL_CLUSTER=\"`hostname`=http://$HOST_IP:2380\""               >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    else
+
+      for line in `curl -s http://\`cat $PATH_CONFIGURE_DIR/cluster_installed\`:2379/v2/members | sed s#{#"\n"{#g | grep name`
+        do
+          NAME=`echo $line | sed s#,\"#"\n",{#g | grep name | awk -F '"' ' {print $3} '`;
+          PEER_URL=`echo $line | sed s#,\"#"\n",{#g | grep peerURLs | awk -F '"' ' {print $3} '`;
+          INITIAL_CLUSTER=`echo "$INITIAL_CLUSTER,$NAME=$PEER_URL"`;
+      done
+      INITIAL_CLUSTER=`echo $INITIAL_CLUSTER | sed s#\^,##g`;
+      echo "ETCD_INITIAL_CLUSTER=\"$INITIAL_CLUSTER,`hostname`=http://$HOST_IP:2380\""
+      echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380\""                         >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+      echo "ETCD_INITIAL_CLUSTER_STATE=\"existing\""                                >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    fi;
+}
+
+# Starting etcd
+create_etcd2_service_func;
+sudo systemctl start etcd2-cluster.service;
+if [ $? -ne 0 ]; then
+    echo -e "\E[31m Etcd2 service is not started!" >&2;tput sgr0;
+    exit 1;
+else
+    echo -e "\E[32m Etcd2 service is started.";tput sgr0;
 fi;
