Added cluster-tocken.

diff --git a/cluster-config b/cluster-config
--- a/cluster-config
+++ b/cluster-config
@@ -1,8 +1,9 @@
 #!/bin/bash
-
+set -vx
 PATH_CONFIGURE_DIR="/etc/smilart";
 PATH_CLUSTER_INSTALLED="$PATH_CONFIGURE_DIR/cluster_installed";
 ETCD_PORT=2379;
+CLUSTER_TOCKEN='';
 
 #exist dialog?
 dialog --clear;
@@ -15,7 +16,9 @@ fi;
 LOG_ERROR[1]="ERROR: Not checked configure server.";
 LOG_ERROR[2]="ERROR: Field 'Ip' is empty.";
 LOG_ERROR[3]="ERROR: Field 'Ip' is incorrect.";
-LOG_ERROR[4]="ERROR: Failed to ping the etcd cluster."
+LOG_ERROR[4]="ERROR: Failed to ping the etcd cluster.";
+LOG_ERROR[5]="ERROR: Field 'Tocken' is empty.";
+LOG_ERROR[6]="ERROR: Incorect string in field 'Tocken'. String can only be letters and numbers.";
 #********Genetate tempfiles from dialog*********#
 tempfile() {
     tempprefix=$(basename "$0");
@@ -80,6 +83,7 @@ function valid_ip_func() {
 #****************CONFIGURE CLUSTER**************#
 EXIT_FORM="true";
 FORM_IP='';
+FORM_TOCKEN='';
 while [[ $EXIT_FORM == "true" ]];do
   # Store data to $cmd variable
   exec 3>&1
@@ -95,15 +99,16 @@ while [[ $EXIT_FORM == "true" ]];do
   exec 3>&-
 
   if [[ $DIALOG_RETURN_VALUE == 1 || $DIALOG_RETURN_VALUE == 255 ]]; then
-    run_at_break;
+      run_at_break;
   fi;
 
-  #Empty ?
+  #Empty?
   if [[ -z "$FORM_CLUSTER" ]]; then
-     error_func "${LOG_ERROR[1]}";
-     continue
+      error_func "${LOG_ERROR[1]}";
+      continue
   fi
 
+  #Master or slave?
   if [[ "$FORM_CLUSTER" == "2" ]];then
       # display values just entered
       # open fd
@@ -114,11 +119,11 @@ while [[ $EXIT_FORM == "true" ]];do
         --ok-label "OK" \
         --title "Smilart Operating System" \
         --form "\nEnter address from etcd-server:" \
-       0 0 0 \
-       "Ip:              " 1 1 "$FORM_IP"           1 20 30 0 \
-       2>&1 1>&3)
-       DIALOG_RETURN_VALUE=$?
-       exec 3>&-
+      0 0 0 \
+      "Ip:              " 1 1 "$FORM_IP"           1 20 30 0 \
+      2>&1 1>&3)
+      DIALOG_RETURN_VALUE=$?
+      exec 3>&-
 
       #ESC in dialog?
       if [[ $DIALOG_RETURN_VALUE == 1 || $DIALOG_RETURN_VALUE == 255 ]]; then
@@ -143,7 +148,8 @@ while [[ $EXIT_FORM == "true" ]];do
       fi;
       CLUSTER_INSTALLED="$FORM_IP"
   else
-      CLUSTER_INSTALLED="single"
+      CLUSTER_TOCKEN=SmilartCluster`date +%s`;
+      CLUSTER_INSTALLED="single";
   fi;
 
   EXIT_FORM="false";
@@ -163,11 +169,13 @@ fi;
 HOST_IP=`cat /etc/systemd/network/static.network | grep 'Address' | sed s#"Address="##g | awk -F '/' ' {print $1} '`;
 if [[ $CLUSTER_INSTALLED != "single" ]]; then
     MEMBERS_MASTER=`curl -s http://$CLUSTER_INSTALLED:2379/v2/members | sed s#{#"\n"{#g | grep name`;
+    CLUSTER_TOCKEN=`etcdctl --peers=$CLUSTER_INSTALLED:$ETCD_PORT get _cluster-tocken`;
     etcdctl --peers=$CLUSTER_INSTALLED:$ETCD_PORT member add `hostname` http://$HOST_IP:2380;
     if [ $? -ne 0 ]; then
         echo -e "\E[31m Error configuring master etcd!" >&2;tput sgr0;
         exit 1;
     fi;
+    
 fi;
 
 #Stopping daemon etcd
@@ -180,40 +188,38 @@ sudo systemctl enable etcd2.service > /dev/null;
 sudo rm -f -R /var/lib/etcd2/* > /dev/null 2>&1;
 
 # Generating env to services
+  # Configure etcd2.service
+  echo "ETCD_DATA_DIR=\"/var/lib/etcd2\""                                        > $PATH_CONFIGURE_DIR/etcd2.service.env;
+  echo "ETCD_NAME=\"`hostname`\""                                               >> $PATH_CONFIGURE_DIR/etcd2.service.env;
+  echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380\""                         >> $PATH_CONFIGURE_DIR/etcd2.service.env;
+  echo "ETCD_LISTEN_CLIENT_URLS=\"http://0.0.0.0:2379\""                        >> $PATH_CONFIGURE_DIR/etcd2.service.env;
+  echo "ETCD_ADVERTISE_CLIENT_URLS=\"http://$HOST_IP:2379\""                    >> $PATH_CONFIGURE_DIR/etcd2.service.env;
 
-    # Configure etcd2.service
-    echo "ETCD_DATA_DIR=\"/var/lib/etcd2\""                                        > $PATH_CONFIGURE_DIR/etcd2.service.env;
-    echo "ETCD_NAME=\"`hostname`\""                                               >> $PATH_CONFIGURE_DIR/etcd2.service.env;
-    echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380\""                         >> $PATH_CONFIGURE_DIR/etcd2.service.env;
-    echo "ETCD_LISTEN_CLIENT_URLS=\"http://0.0.0.0:2379\""                        >> $PATH_CONFIGURE_DIR/etcd2.service.env;
-    echo "ETCD_ADVERTISE_CLIENT_URLS=\"http://$HOST_IP:2379\""                    >> $PATH_CONFIGURE_DIR/etcd2.service.env;
+  # etcd2 prestart configure
+  echo "ETCD_DATA_DIR=\"/var/lib/etcd2\""                                          > $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+  echo "ETCD_NAME=\"`hostname`\""                                                 >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+  echo "ETCD_LISTEN_CLIENT_URLS=\"http://0.0.0.0:2379\""                          >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+  echo "ETCD_ADVERTISE_CLIENT_URLS=\"http://$HOST_IP:2379\""                      >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_INITIAL_CLUSTER_TOKEN=\"$CLUSTER_TOCKEN\""                         >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
 
-    # etcd2 prestart configure
+  if [[ "$CLUSTER_INSTALLED" == 'single' ]];then
+    echo "ETCD_INITIAL_ADVERTISE_PEER_URLS=\"http://$HOST_IP:2380\""              >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380,http://127.0.0.1:2380\""   >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_INITIAL_CLUSTER_STATE=\"new\""                                     >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_INITIAL_CLUSTER=\"`hostname`=http://$HOST_IP:2380\""               >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+  else
+    for line in $MEMBERS_MASTER; do
+      NAME=`echo $line | sed s#,\"#"\n",{#g | grep name | awk -F '"' ' {print $3} '`;
+      PEER_URL=`echo $line | sed s#,\"#"\n",{#g | grep peerURLs | awk -F '"' ' {print $3} '`;
+      INITIAL_CLUSTER=`echo "$INITIAL_CLUSTER,$NAME=$PEER_URL"`;
+    done
+    INITIAL_CLUSTER=`echo $INITIAL_CLUSTER | sed s#\^,##g`;
 
-    echo "ETCD_DATA_DIR=\"/var/lib/etcd2\""                                          > $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-    echo "ETCD_NAME=\"`hostname`\""                                                 >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-    echo "ETCD_LISTEN_CLIENT_URLS=\"http://0.0.0.0:2379\""                          >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-    echo "ETCD_ADVERTISE_CLIENT_URLS=\"http://$HOST_IP:2379\""                      >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-    echo "ETCD_INITIAL_CLUSTER_TOKEN=\"smilart-cluster\""                           >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-    if [[ "$CLUSTER_INSTALLED" == 'single' ]];then
-
-      echo "ETCD_INITIAL_ADVERTISE_PEER_URLS=\"http://$HOST_IP:2380\""              >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-      echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380,http://127.0.0.1:2380\""   >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-      echo "ETCD_INITIAL_CLUSTER_STATE=\"new\""                                     >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-      echo "ETCD_INITIAL_CLUSTER=\"`hostname`=http://$HOST_IP:2380\""               >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-    else
-
-      for line in $MEMBERS_MASTER; do
-          NAME=`echo $line | sed s#,\"#"\n",{#g | grep name | awk -F '"' ' {print $3} '`;
-          PEER_URL=`echo $line | sed s#,\"#"\n",{#g | grep peerURLs | awk -F '"' ' {print $3} '`;
-          INITIAL_CLUSTER=`echo "$INITIAL_CLUSTER,$NAME=$PEER_URL"`;
-      done
-      INITIAL_CLUSTER=`echo $INITIAL_CLUSTER | sed s#\^,##g`;
-      echo "ETCD_INITIAL_CLUSTER=\"$INITIAL_CLUSTER,`hostname`=http://$HOST_IP:2380\"" \
-                                                                                    >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-      echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380\""                         >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-      echo "ETCD_INITIAL_CLUSTER_STATE=\"existing\""                                >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
-    fi;
+    echo "ETCD_INITIAL_CLUSTER=\"$INITIAL_CLUSTER,`hostname`=http://$HOST_IP:2380\"" \
+                                                                                  >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_LISTEN_PEER_URLS=\"http://$HOST_IP:2380\""                         >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+    echo "ETCD_INITIAL_CLUSTER_STATE=\"existing\""                                >> $PATH_CONFIGURE_DIR/etcd2-cluster.service.env;
+  fi;
 
 # Starting etcd
 sudo systemctl start etcd2-cluster.service;
@@ -222,6 +228,27 @@ if [ $? -ne 0 ]; then
     exit 1;
 else
     echo -e "\E[32m Etcd2 service is started.";tput sgr0;
+fi;
+
+# Post start etcd
+if [[ $CLUSTER_INSTALLED == "single" ]]; then
+  #While. Reconnect to local etcd
+  i=0;
+  while [ $i -lt 3 ]; do
+    i=$[$i+1];
+    etcdctl set _cluster-tocken $CLUSTER_TOCKEN >/dev/null 2>&1;
+    if [ $? -ne 0 ];then
+      sleep 3;
+      continue;
+    else
+      break;
+    fi;
+  done
+  if [ $i -eq 4 ];then
+    echo -e "\E[31mERROR: Creating key 'cluster-tocken' is aborted. Maybe not start local etcd." >&2;tput sgr0;
+    exit 1;
+  fi;
+  unset i;
 fi;
 
 run_at_exit;
