Refactoring. Fixed wait to ping hostname. DNS is exist in configuring.

diff --git a/network-config b/network-config
--- a/network-config
+++ b/network-config
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #Set debug mode:
-#set -vx
+set -vx
 
 #exist dialog?
 dialog --clear;
@@ -17,8 +17,8 @@ NETWORK_INSTALLED="/etc/smilart/network_installed";
 #**************log ERROR************************#
 LOG_ERROR[1]="ERROR: Not checked interface.";
 LOG_ERROR[2]="ERROR: Found symbol '_' in fields.";
-LOG_ERROR[3]="ERROR: Field 'Mask' is incorrect.";
-LOG_ERROR[4]="ERROR: Incorrect hostname.";
+LOG_ERROR[3]="ERROR: Field 'Mask' is'nt valid.";
+LOG_ERROR[4]="ERROR: Hostname is'nt valid.";
 LOG_ERROR[5]="ERROR: Cannot change hostname.";
 LOG_ERROR[6]="ERROR: Cannot connect to local etcd.";
 LOG_ERROR[7]="ERROR: This machine is a cluster.";
@@ -31,6 +31,7 @@ tempfile() {
     mktemp /tmp/${tempprefix}.XXXXXX;
 }
 
+#Color sheme
 TMP_DIALOG_WARN=$(tempfile)
 TMP_DIALOG_MENU=$(tempfile)
 TMP_DIALOG_ERROR=$(tempfile)
@@ -38,33 +39,33 @@ TMP_DIALOG_ERROR=$(tempfile)
 echo "
 dialog_color = (YELLOW,WHITE,ON)
 title_color = (RED,WHITE,ON)
-" > $TMP_DIALOG_WARN
+" > ${TMP_DIALOG_WARN}
 
 echo "
 bindkey formbox   TAB  form_next
 bindkey formfield TAB  form_next
 bindkey formfield BTAB form_prev
 bindkey formbox   BTAB form_prev
-" > $TMP_DIALOG_MENU;
+" > ${TMP_DIALOG_MENU};
 
 echo "
 dialog_color = (RED,WHITE,OFF)
 title_color = (RED,WHITE,ON)
-" > $TMP_DIALOG_ERROR
+" > ${TMP_DIALOG_ERROR}
 
 # Function at break script
 run_at_break(){
   sleep 1;
-  DIALOGRC="$TMP_DIALOG_WARN" \
+  DIALOGRC="${TMP_DIALOG_WARN}" \
     dialog --ok-label "OK" \
            --msgbox "\nWARN: Network is not configured." 10 50;
-  rm -f $TMP_DIALOG_MENU $TMP_DIALOG_ERROR $TMP_DIALOG_WARN;
+  rm -f ${TMP_DIALOG_MENU} ${TMP_DIALOG_ERROR} ${TMP_DIALOG_WARN};
   exit 1;
 }
 
 # Function at exit script
 run_at_exit(){
-  rm -f $TMP_DIALOG_MENU $TMP_DIALOG_ERROR $TMP_DIALOG_WARN
+  rm -f ${TMP_DIALOG_MENU} ${TMP_DIALOG_ERROR} ${TMP_DIALOG_WARN}
   exit 0;
 }
 
@@ -74,7 +75,7 @@ trap 'run_at_break' SIGHUP SIGINT SIGTERM
 # echo ERROR to dialog
 # error_func <text>
 error_func() {
-  DIALOGRC="$TMP_DIALOG_ERROR" \
+  DIALOGRC="${TMP_DIALOG_ERROR}" \
     dialog --msgbox "\n$1" 10 50
 }
 
@@ -82,8 +83,8 @@ error_func() {
 # valid_ip_func <ip> <name field>
 # valid_ip_func 192.168.1.1 Ip
 function valid_ip_func() {
-  if ! [[ $1 =~ ^(25[0-5]|2[0-4][i0-9]|[0-1][0-9]{2}|[0-9]{2}|[0-9])(\.(25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[0-9]{2}|[0-9])){3}$ ]]; then
-    error_func "ERROR: Incorrectly field '$2'.";
+  if ! [[ $1 =~ ^(25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[0-9]{2}|[0-9])(\.(25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[0-9]{2}|[0-9])){3}$ ]]; then
+    error_func "ERROR: Field '$2' is'nt valid.";
     continue
   fi;
 }
@@ -163,7 +164,7 @@ fi;
 
 #****************CONFIGURE INTERFACE**************#
 EXIT_FORM="0";
-while [[ $EXIT_FORM == "0" ]];do
+while [[ ${EXIT_FORM} == "0" ]];do
   # search current interfaces
   inet=`ls /sys/class/net | grep -v "\`ls /sys/devices/virtual/net\`"`;
 
@@ -179,7 +180,7 @@ while [[ $EXIT_FORM == "0" ]];do
     else
       CONNECT_i="$i -";
     fi;
-    if [[ $MENU_OPTIONS == '' ]];then
+    if [[ ${MENU_OPTIONS} == '' ]];then
       MENU_OPTIONS="${CONNECT_i} on ";
     else
       MENU_OPTIONS="${MENU_OPTIONS} ${CONNECT_i} off ";
@@ -188,7 +189,7 @@ while [[ $EXIT_FORM == "0" ]];do
 
   # Store data to variable
   exec 3>&1
-  FORM_INTERFACE=$(DIALOGRC="$TMP_DIALOG_MENU" dialog --clear \
+  FORM_INTERFACE=$(DIALOGRC="${TMP_DIALOG_MENU}" dialog --clear \
     --ok-label "Next" \
     --title "Smilart Operating System" \
     --radiolist "\nSelect the network interface to configure" \
@@ -198,12 +199,12 @@ while [[ $EXIT_FORM == "0" ]];do
   DIALOG_RETURN_VALUE=$?
   exec 3>&-
 
-  if [[ $DIALOG_RETURN_VALUE == 1 || $DIALOG_RETURN_VALUE == 255 ]]; then 
+  if [[ ${DIALOG_RETURN_VALUE} == 1 || ${DIALOG_RETURN_VALUE} == 255 ]]; then 
     run_at_break; 
   fi;
 
-  #Correct interface?
-  if [[ -z "$FORM_INTERFACE" ]]; then
+  #Valid interface?
+  if [[ -z "${FORM_INTERFACE}" ]]; then
      error_func "${LOG_ERROR[1]}";
      continue
   else
@@ -217,18 +218,21 @@ done;
 EXIT_FORM="0";
 
 # Writing old configure
-  FORM_IP=``
 if [[ `hostname` == 'localhost' ]];then
   FORM_HOSTNAME="";
 else
   FORM_HOSTNAME="`hostname`";
 fi
+
 if [ -e "${PATH_SYSTEM_NETWORK}/${FORM_INTERFACE}.network" ];then
   CONFIGURE_TO_FILE=`cat ${PATH_SYSTEM_NETWORK}/${FORM_INTERFACE}.network`;
-  FORM_IP=`echo "$CONFIGURE_TO_FILE" | grep 'Address' | sed s#"Address="##g | awk -F '/' ' {print $1} '`;
-  FORM_MASK=/`echo "$CONFIGURE_TO_FILE" | grep 'Address' | sed s#"Address="##g | awk -F '/' ' {print $2} '`;
-  FORM_GATEWAY=`echo "$CONFIGURE_TO_FILE" | grep 'Gateway' | sed s#"Gateway="##g`;
-  FORM_DNS=`cat "$PATH_DNS_HOST"`;
+  FORM_IP=`echo "${CONFIGURE_TO_FILE}" | grep 'Address' | sed s#"Address="##g | awk -F '/' ' {print $1} '`;
+  FORM_MASK=/`echo "${CONFIGURE_TO_FILE}" | grep 'Address' | sed s#"Address="##g | awk -F '/' ' {print $2} '`;
+  FORM_GATEWAY=`echo "${CONFIGURE_TO_FILE}" | grep 'Gateway' | sed s#"Gateway="##g`;
+  FORM_DNS=`cat "${PATH_DNS_HOST}"`;
+  if [ -z ${FORM_DNS} ];then
+      FORM_DNS='8.8.8.8';
+  fi;
 else
   FORM_IP='';
   FORM_MASK='';
@@ -236,58 +240,61 @@ else
   FORM_DNS='';
 fi
 
-while [[ $EXIT_FORM == "0" ]];do
+while [[ ${EXIT_FORM} == "0" ]];do
 
-  if [ -f $NETWORK_INSTALLED ];then
+  if [ -f ${NETWORK_INSTALLED} ];then
       exec 3>&1
       # Store data to $DIALOG_STRING variable
-      DIALOG_STRING=$(DIALOGRC="$TMP_DIALOG_MENU" dialog --clear \
+      DIALOG_STRING=$(DIALOGRC="${TMP_DIALOG_MENU}" dialog --clear \
         --ok-label "OK" \
         --title "Smilart Operating System" \
-        --form "\nEnter network settings \n \n Hostname:          $FORM_HOSTNAME\n" \
+        --form "\nEnter network settings \n \n Hostname:          ${FORM_HOSTNAME}\n" \
        0 0 0 \
-       "Ip:              " 1 1 "$FORM_IP"           1 20 30 0 \
-       "Mask:            " 3 1 "$FORM_MASK"         3 20 30 0 \
-       "Gateway:         " 5 1 "$FORM_GATEWAY"      5 20 30 0 \
-       "DNS:             " 7 1 "$FORM_DNS"          7 20 30 0 \
+       "Ip:              " 1 1 "${FORM_IP}"           1 20 30 0 \
+       "Mask:            " 3 1 "${FORM_MASK}"         3 20 30 0 \
+       "Gateway:         " 5 1 "${FORM_GATEWAY}"      5 20 30 0 \
+       "DNS:             " 7 1 "${FORM_DNS}"          7 20 30 0 \
        2>&1 1>&3)
       DIALOG_RETURN_VALUE=$?
       exec 3>&-
+      #one field if empty
+      #DIALOG_STRING="_"+$DIALOG_STRING;
   else
       exec 3>&1
       # Store data to $DIALOG_STRING variable
-      DIALOG_STRING=$(DIALOGRC="$TMP_DIALOG_MENU" dialog --clear \
+      DIALOG_STRING=$(DIALOGRC="${TMP_DIALOG_MENU}" dialog --clear \
       --ok-label "OK" \
       --title "Smilart Operating System" \
       --form "\nEnter network settings" \
       0 0 0 \
-      "Hostname:        " 1 1 "$FORM_HOSTNAME"     1 20 30 0 \
-      "Ip:              " 3 1 "$FORM_IP"           3 20 30 0 \
-      "Mask:            " 5 1 "$FORM_MASK"         5 20 30 0 \
-      "Gateway:         " 7 1 "$FORM_GATEWAY"      7 20 30 0 \
-      "DNS:             " 9 1 "$FORM_DNS"          9 20 30 0 \
+      "Hostname:        " 1 1 "${FORM_HOSTNAME}"     1 20 30 0 \
+      "Ip:              " 3 1 "${FORM_IP}"           3 20 30 0 \
+      "Mask:            " 5 1 "${FORM_MASK}"         5 20 30 0 \
+      "Gateway:         " 7 1 "${FORM_GATEWAY}"      7 20 30 0 \
+      "DNS:             " 9 1 "${FORM_DNS}"          9 20 30 0 \
        2>&1 1>&3)
       DIALOG_RETURN_VALUE=$?
       exec 3>&-
   fi;
 
-  if [[ $DIALOG_RETURN_VALUE == 1 || $DIALOG_RETURN_VALUE == 255 ]]; then
+  if [[ ${DIALOG_RETURN_VALUE} == 1 || ${DIALOG_RETURN_VALUE} == 255 ]]; then
     run_at_break;
   fi;
 
   # exist "_" in form?
-  if [[ -n `echo "$DIALOG_STRING" | grep "_"` ]];then
+  if [[ -n `echo "${DIALOG_STRING}" | grep "_"` ]];then
         error_func "${LOG_ERROR[2]}";
         continue
   fi;
   #symbols "\n" to "_"
-  DIALOG_STRING=`echo "$DIALOG_STRING" | tr "\n" "_"`
+  DIALOG_STRING=`echo "${DIALOG_STRING}" | tr "\n" "_"`
 
   # convert DIALOG_STRING to variables
   OIFS=$IFS
   IFS='_'
-  DIALOG_STRING=($DIALOG_STRING)
-  if [ -f $PATH_DNS_HOST ];then
+  DIALOG_STRING=(${DIALOG_STRING})
+  if [ -f ${PATH_DNS_HOST} ];then
+      #FORM_HOSTNAME=${DIALOG_STRING[0]};
       FORM_IP=${DIALOG_STRING[0]};
       FORM_MASK=${DIALOG_STRING[1]};
       FORM_GATEWAY=${DIALOG_STRING[2]};
@@ -301,20 +308,20 @@ while [[ $EXIT_FORM == "0" ]];do
   fi;
   IFS=$OIFS
 
-  #*********Correct ip*********#
+  #*********Valid ip*********#
   # empty field?
-  field_not_empty_func "$FORM_IP" Ip;
+  field_not_empty_func "${FORM_IP}" Ip;
 
   # It is ip format?
-  valid_ip_func "$FORM_IP" Ip;
+  valid_ip_func "${FORM_IP}" Ip;
 
-  #*********Correct mask*********#
+  #*********Valid mask*********#
   # empty field?
-  field_not_empty_func "$FORM_MASK" Mask;
+  field_not_empty_func "${FORM_MASK}" Mask;
 
   # Valid mask?
-  if ! [[ $FORM_MASK =~ ^[\/][0-3]{,1}[0-9]$ && ${FORM_MASK:1} -le 32 ]];then
-    valid_ip_func "$FORM_MASK" Mask;
+  if ! [[ ${FORM_MASK} =~ ^[\/][0-3]{,1}[0-9]$ && ${FORM_MASK:1} -le 32 ]];then
+    valid_ip_func "${FORM_MASK}" Mask;
     OIFS=$IFS
     IFS="."
     BIN_MASK=""
@@ -326,35 +333,40 @@ while [[ $EXIT_FORM == "0" ]];do
       BIN_MASK+=$(printf "%08d" $(echo "ibase = 10; obase = 2 ; $i" | bc));
     done
     IFS=$OIFS;
-    if [[ $BIN_MASK =~ (1*0+1) ]];then
+    if [[ ${BIN_MASK} =~ (1*0+1) ]];then
       error_func "${LOG_ERROR[3]}";
       continue
     fi;
-    FORM_MASK=`mask2cidr_func "$FORM_MASK"`;
+    FORM_MASK=`mask2cidr_func "${FORM_MASK}"`;
   fi;
 
-  #*********Correct gateway*********#
+  #*********Valid gateway*********#
   if [[ -n "$FORM_GATEWAY" ]]; then
     # It is ip format?
-    valid_ip_func "$FORM_GATEWAY" Gateway;
+    valid_ip_func "${FORM_GATEWAY}" Gateway;
   fi;
+  
+  
 
-  #*********Correct dns*********#
+  #*********Valid dns*********#
+  # empty field?
+  field_not_empty_func "${FORM_DNS}" DNS;
+    
   if [[ -n "$FORM_DNS" ]]; then
     # It is ip format?
-    valid_ip_func "$FORM_DNS" DNS;
-    if [[ "$FORM_DNS" =~ ^'127' ]];then
+    valid_ip_func "${FORM_DNS}" DNS;
+    if [[ "${FORM_DNS}" =~ ^'127' ]];then
         error_func "Dns address can not be 'localhost'.";
         continue
     fi;
   fi;
 
-  #*********Correct hostname*********#
+  #*********Valid hostname*********#
   # empty field?
-  field_not_empty_func "$FORM_HOSTNAME" Hostname;
+  field_not_empty_func "${FORM_HOSTNAME}" Hostname;
 
   #valid hostname?
-  test_hostname_func $FORM_HOSTNAME;
+  test_hostname_func ${FORM_HOSTNAME};
 
   EXIT_FORM="1";
 done;
@@ -365,17 +377,17 @@ done;
 #Create config network
 echo "
 [Match]
-Name=$FORM_INTERFACE
+Name=${FORM_INTERFACE}
 
 [Network]
-Address=$FORM_IP$FORM_MASK
-`if [[ -n $FORM_GATEWAY ]];then echo "Gateway=$FORM_GATEWAY"; fi`
+Address=${FORM_IP}${FORM_MASK}
+`if [[ -n ${FORM_GATEWAY} ]];then echo "Gateway=${FORM_GATEWAY}"; fi`
 DNS=127.0.0.1
 Domains=smilart.local
-" > $PATH_SYSTEM_NETWORK/$FORM_INTERFACE.network;
+" > ${PATH_SYSTEM_NETWORK}/${FORM_INTERFACE}.network;
 
 # Delete old config interface
-while ip -f inet addr del dev $FORM_INTERFACE >/dev/null 2>&1;do 
+while ip -f inet addr del dev ${FORM_INTERFACE} >/dev/null 2>&1;do 
 sleep 0.1;
 done;
 
@@ -383,7 +395,7 @@ done;
 sudo systemctl restart systemd-networkd;
 
 #Set hostname
-sudo hostnamectl set-hostname $FORM_HOSTNAME;
+sudo hostnamectl set-hostname ${FORM_HOSTNAME};
 if [[ $? != 0 ]];then
     error_func "${LOG_ERROR[9]}";
     exit 1;
@@ -391,11 +403,11 @@ fi;
 
 #Save dns in temporary file to configure dns server
 mkdir -p /etc/smilart > /dev/null 2>&1;
-if [[ -n $FORM_DNS ]];then
-  echo "$FORM_DNS" > $PATH_DNS_HOST;
+if [[ -n ${FORM_DNS} ]];then
+  echo "${FORM_DNS}" > ${PATH_DNS_HOST};
 fi;
 
-echo "$FORM_INTERFACE" > $NETWORK_INSTALLED;
+echo "${FORM_INTERFACE}" > ${NETWORK_INSTALLED};
 
 #Restart skydns
 clear;
