Changed error messages to dialog.

diff --git a/network-config b/network-config
--- a/network-config
+++ b/network-config
@@ -22,6 +22,8 @@ LOG_ERROR[4]="ERROR: Incorrect hostname.";
 LOG_ERROR[5]="ERROR: Cannot change hostname.";
 LOG_ERROR[6]="ERROR: Not connect to local etcd.";
 LOG_ERROR[7]="ERROR: This machine is a cluster.";
+LOG_ERROR[8]="ERROR: Not started skydns service. See 'journalctl -u skydns' for details.";
+LOG_ERROR[9]="ERROR: Hostname to server not changed.";
 #********Genetate tempfiles from dialog*********#
 tempfile() {
     tempprefix=$(basename "$0");
@@ -374,6 +376,10 @@ sudo systemctl restart systemd-networkd;
 
 #Set hostname
 sudo hostnamectl set-hostname $FORM_HOSTNAME;
+if [[ $? != 0 ]];then
+    error_func "${LOG_ERROR[9]}";
+    exit 1;
+fi;
 
 #Save dns in temporary file to configure dns server
 mkdir -p /etc/smilart > /dev/null 2>&1;
@@ -384,5 +390,9 @@ echo "$FORM_INTERFACE" > $NETWORK_INSTALLED;
 clear;
 echo 'Restarting skydns.service';
 sudo systemctl restart skydns;
+if [[ $? != 0 ]];then
+    error_func "${LOG_ERROR[8]}";
+    exit 1;
+fi;
 
 run_at_exit;
